name = "cf-botasaurus"
main = "src/index.ts"
compatibility_date = "2023-03-26"

[vars]
OPENAI_CHAT_MODEL = "gpt-3.5-turbo"
OPENAI_CHAT_PROMPT = "Short, concise, accurate, sarcastic and funny answers only"

# Secrets:
# - OPENAI_API_KEY
# - TELEGRAM_BOT_KEY
